/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRepertoireRouteImport } from './routes/app.repertoire'
import { Route as AppOpeningsRouteImport } from './routes/app.openings'
import { Route as AppGamesRouteImport } from './routes/app.games'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepertoireRoute = AppRepertoireRouteImport.update({
  id: '/repertoire',
  path: '/repertoire',
  getParentRoute: () => AppRoute,
} as any)
const AppOpeningsRoute = AppOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/games': typeof AppGamesRoute
  '/app/openings': typeof AppOpeningsRoute
  '/app/repertoire': typeof AppRepertoireRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/games': typeof AppGamesRoute
  '/app/openings': typeof AppOpeningsRoute
  '/app/repertoire': typeof AppRepertoireRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/games': typeof AppGamesRoute
  '/app/openings': typeof AppOpeningsRoute
  '/app/repertoire': typeof AppRepertoireRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/games'
    | '/app/openings'
    | '/app/repertoire'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/games' | '/app/openings' | '/app/repertoire' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/games'
    | '/app/openings'
    | '/app/repertoire'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repertoire': {
      id: '/app/repertoire'
      path: '/repertoire'
      fullPath: '/app/repertoire'
      preLoaderRoute: typeof AppRepertoireRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/openings': {
      id: '/app/openings'
      path: '/openings'
      fullPath: '/app/openings'
      preLoaderRoute: typeof AppOpeningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGamesRoute: typeof AppGamesRoute
  AppOpeningsRoute: typeof AppOpeningsRoute
  AppRepertoireRoute: typeof AppRepertoireRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGamesRoute: AppGamesRoute,
  AppOpeningsRoute: AppOpeningsRoute,
  AppRepertoireRoute: AppRepertoireRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
